---
title: "R Notebook"
output: html_notebook
---
```{r}
library(tidyverse)
library(readr)
library(tidyselect)
library(tidyr)
dogs <- read.csv("dogs.csv")
view(dogs)
```

###The client only counts a valid email address as one ending in ‘.com’. How many survey results have a valid email address.

```{r}
pattern <- ".com"

dogs %>% 
  str_count(pattern)
```

###What’s the average amount spent on dog food for each dog size.
```{r}
dogs %>% 
  select(dog_size, amount_spent_on_dog_food) %>% 
  group_by(dog_size) %>% 
  summarise(avg_spend = mean(amount_spent_on_dog_food))
```
###For owners whose surname starts with a letter in the second half of the alphabet (N onwards) what is the average age of their dog?
```{r}
dogs <- dogs %>% 
  mutate(dog_age = na_if(dog_age, "Less than 20"),
         dog_age = na_if(dog_age, "3,3,5"),
         dog_age = na_if(dog_age, "12+"),
         dog_age = na_if(dog_age, ""),
         drop_na())
  
  
dogs %>% 
  separate(full_name, c("first_name", "second_name"), sep = " ") %>% filter(second_name > "N") %>% 
  mutate(dog_age = as.numeric(dog_age)) %>% 
  summarise(avg_age = mean(dog_age))

unique(dogs$dog_age)
```

```{r}

```

