---
title: "documentation_report"
output: html_document
date: '2022-08-04'
---
The dataset that I have cleaned and analysed came in the form of the 3 .xlsx files, each file being associated with the year of data collection (2015, 2016 & 2017). The data captured outlined the rating of various confectionary items (joy, despair or meh), as well as other factor such as age, country, state, trick or treating status and a timestamp/id to identify distinct participants. 
  Upon starting my data cleaning the first step was to read in the data and give change the variable names to a more suitabel format, in this initial phase I also took time to explore the dataset. Secondly, I removed columns from each dataset which appeared to contain information that didn't relate to confectionary items or the participant who rated them. After this I pivoted the datasets into long format and removed prefixes to column names. The next step was to match column names and types in each dataset in advance of joining them, I also recoded timestamp/ID to reflect the year the data correlated to. After joining the datasets I then dealt with missing values by dropping or coalescing them. My final challenge during data cleaning was to clean the country column which consisted of many spelling variations of each country, to rectify this I had to utilise some hard coding as regex would hugely tie consuming due to the amount of variations.
    The number of ratings acroos the three years is "772,352" which is the same as the total number of rows as I had already dropped NAs from reaction column. The average age of people going out tricking treating after removing implausible values was found to be 35, whereas the average age of those not going trick or treating is 39. Full sized candy bars recieved the most "joy" reactions, broken glowsticks the most "depsair" and lollipops the most "meh". There were 1990 ratings of Starbursts as despair. According to my rating system (joy = +1, meh = 0, despair = -1)
the most popular item for all genders is full is sized candy bars, the same was true overall for each recorded year and each country apart from the UK who preferred cash.    