---
title: "R Notebook"
output: html_notebook
---
```{r}
library(tidyverse)
library(here)
long_decathlon_data <- read.csv(here("clean_data/long_decathlon_data.csv"))
long_decathlon_data <- select(long_decathlon_data, -1)
glimpse(long_decathlon_data)
```
#longest long jump
```{r}
long_decathlon_data %>% 
  select(name, discipline, score) %>% 
  filter(discipline == "long_jump") %>% 
  arrange(desc(score)) %>% 
  head(1)
```
#average 100m time in each competition
```{r}
long_decathlon_data %>% 
  filter(discipline == "x100m") %>% 
  group_by(competition) %>% 
  summarise(avg_time = mean(score)) %>% 
  mutate(avg_time = as.numeric(avg_time))
```
#highest points total across both competitionsc
```{r}
long_decathlon_data %>% 
  group_by(name) %>% 
  mutate(total_points = mean(points)*2) %>% #work aorund as sum adds all points
  arrange(desc(total_points)) %>% 
  select(name, total_points) %>%
  head(1)
```
#top 3 shotputters and scores in each comp
```{r}
long_decathlon_data %>% 
  filter(discipline == "shot_put", competition == "Decastar") %>% 
  arrange(desc(score)) %>% 
  head(3)

long_decathlon_data %>% 
  filter(discipline == "shot_put", competition == "OlympicG") %>% 
  arrange(desc(score)) %>% 
  head(3)
```
#avg points for 400m runners based on time 
```{r}
long_decathlon_data %>% 
  mutate (time_category = if_else(score >= 50.00, "slow", "fast"))%>% group_by(time_category) %>% 
  summarise(mean(points))
```

